var searchData=
[
  ['safely_20test_20without_20polluting_20production_0',['Safely test without polluting production',['../_integration_testing.html#WhyTest',1,'']]],
  ['scenario_1',['Match3 Level Scenario',['../_item_exchange.html#Example4',1,'']]],
  ['scenario_2010_3a_20advanced_20item_20goal_20tracking_2',['Scenario 10: Advanced Item &amp; Goal Tracking',['../_dummy_game_integration.html#Scenario_10',1,'']]],
  ['scenario_2011_3a_20custom_20error_20reporting_3',['Scenario 11: Custom Error Reporting',['../_dummy_game_integration.html#Scenario_11',1,'']]],
  ['scenario_201_3a_20first_20launch_20consent_4',['Scenario 1: First Launch &amp; Consent',['../_dummy_game_integration.html#Scenario_1',1,'']]],
  ['scenario_202_3a_20player_20registration_20sign_20in_5',['Scenario 2: Player Registration &amp; Sign-In',['../_dummy_game_integration.html#Scenario_2',1,'']]],
  ['scenario_203_3a_20entering_20main_20menu_20changing_20language_6',['Scenario 3: Entering Main Menu &amp; Changing Language',['../_dummy_game_integration.html#Scenario_3',1,'']]],
  ['scenario_204_3a_20ftue_20milestones_20tracking_7',['Scenario 4: FTUE Milestones Tracking',['../_dummy_game_integration.html#Scenario_4',1,'']]],
  ['scenario_205_3a_20level_20start_20completion_8',['Scenario 5: Level Start &amp; Completion',['../_dummy_game_integration.html#Scenario_5',1,'']]],
  ['scenario_206_3a_20in_20game_20combat_20power_20ups_9',['Scenario 6: In-Game Combat &amp; Power-Ups',['../_dummy_game_integration.html#Scenario_6',1,'']]],
  ['scenario_207_3a_20store_20purchases_20iap_10',['Scenario 7: Store Purchases (IAP)',['../_dummy_game_integration.html#Scenario_7',1,'']]],
  ['scenario_208_3a_20daily_20resets_11',['Scenario 8: Daily Resets',['../_dummy_game_integration.html#Scenario_8',1,'']]],
  ['scenario_209_3a_20non_20unity_20ui_20buttons_20window_20flow_12',['Scenario 9: Non Unity.UI Buttons &amp; Window Flow',['../_dummy_game_integration.html#Scenario_9',1,'']]],
  ['scenarios_13',['Integration Scenarios',['../_dummy_game_integration.html#IntegrationScenarios',1,'']]],
  ['sdk_20integration_20testing_14',['SDK Integration Testing',['../_integration_testing.html',1,'']]],
  ['settlement_15',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../_item_exchange.html#Example9',1,'']]],
  ['setuserconsent_16',['SetUserConsent',['../class_keewano_s_d_k.html#a24c255658725d19b5c47654aeb8c1f17',1,'KeewanoSDK']]],
  ['setuserconsent_20method_17',['SetUserConsent Method',['../_data_privacy.html#DP_method',1,'']]],
  ['setuserid_18',['SetUserId',['../class_keewano_s_d_k.html#ae320ed2c960ce5635e229c14da73ad6d',1,'KeewanoSDK.SetUserId(UInt64 uid)'],['../class_keewano_s_d_k.html#a17d1653b4870dd7b81a15e38282fc899',1,'KeewanoSDK.SetUserId(Guid uid)']]],
  ['shop_3a_20pay_20with_20voucher_20or_20credits_20stamp_20card_19',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../_item_exchange.html#Example7',1,'']]],
  ['sided_20transaction_20',['Sided Transaction',['../_item_exchange.html#Example2',1,'Player Loses a Broken Sword (One-Sided Transaction)'],['../_item_exchange.html#Example3',1,'Player Receives a Reward (One-Sided Transaction)']]],
  ['sign_20in_21',['Scenario 2: Player Registration &amp; Sign-In',['../_dummy_game_integration.html#Scenario_2',1,'']]],
  ['spends_205_20gold_20coins_20and_20a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_22',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../_item_exchange.html#Example1',1,'']]],
  ['stamp_20card_23',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../_item_exchange.html#Example7',1,'']]],
  ['start_20completion_24',['Scenario 5: Level Start &amp; Completion',['../_dummy_game_integration.html#Scenario_5',1,'']]],
  ['start_20guide_25',['Quick Start Guide',['../_quick_start.html',1,'']]],
  ['step_20by_20step_20example_20integration_26',['Step-by-Step Example Integration',['../_dummy_game_integration.html',1,'']]],
  ['step_20example_20integration_27',['Step-by-Step Example Integration',['../_dummy_game_integration.html',1,'']]],
  ['store_20purchases_20iap_28',['Scenario 7: Store Purchases (IAP)',['../_dummy_game_integration.html#Scenario_7',1,'']]],
  ['support_20team_29',['User Balance Fix Reset by Support Team',['../_item_exchange.html#Example6',1,'']]],
  ['sword_20one_20sided_20transaction_30',['Player Loses a Broken Sword (One-Sided Transaction)',['../_item_exchange.html#Example2',1,'']]]
];
