var searchData=
[
  ['t_20call_20for_20new_20users_0',['Don&apos;t Call for New Users',['../ExistingGameIntegration.html#existing_warn_new_users',1,'']]],
  ['team_1',['User Balance Fix Reset by Support Team',['../ItemExchange.html#Example6',1,'']]],
  ['test_20without_20polluting_20production_2',['Safely test without polluting production',['../IntegrationTesting.html#WhyTest',1,'']]],
  ['testing_3',['SDK Integration Testing',['../IntegrationTesting.html',1,'']]],
  ['the_20ad_20revenue_4',['ReportAdRevenue - Track the Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'']]],
  ['the_20complete_20purchase_20flow_5',['The Complete Purchase Flow',['../InAppPurchases.html#iap_flow',1,'']]],
  ['the_20items_20delivered_6',['Step 2: ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['the_20method_7',['The Method',['../ExistingGameIntegration.html#existing_solution',1,'']]],
  ['the_20monetary_20transaction_8',['Step 1: ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['the_20two_20iap_20steps_9',['The Two IAP Steps',['../InAppPurchases.html#iap_methods',1,'']]],
  ['the_20two_20subscription_20steps_10',['The Two Subscription Steps',['../SubscriptionRevenue.html#sub_methods',1,'']]],
  ['these_20two_20steps_20separated_11',['Why Are These Two Steps Separated?',['../InAppPurchases.html#iap_why_separated',1,'']]],
  ['this_20method_12',['When to Use This Method',['../ExistingGameIntegration.html#existing_when',1,'']]],
  ['time_20user_20experience_20ftue_13',['First-Time User Experience (FTUE)',['../onboarding_milestone.html#ftue_tracking',1,'']]],
  ['to_20double_20reward_14',['Scenario 4: Daily Bonus - Watch to Double Reward',['../AdRevenue.html#ad_scenario_daily_bonus',1,'']]],
  ['to_20get_201_20vial_20of_20eternal_20life_15',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['to_20refill_16',['Scenario 2: Out of Energy - Watch to Refill',['../AdRevenue.html#ad_scenario_rewarded_energy',1,'']]],
  ['to_20use_20custom_20tutorial_20events_17',['When to Use Custom Tutorial Events',['../onboarding_milestone.html#tutorial_scenario',1,'']]],
  ['to_20use_20reportonboardingmilestone_18',['When to Use ReportOnboardingMilestone',['../onboarding_milestone.html#ftue_when',1,'']]],
  ['to_20use_20this_20method_19',['When to Use This Method',['../ExistingGameIntegration.html#existing_when',1,'']]],
  ['track_20rewarded_20ad_20items_20',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['track_20subscriber_20rewards_21',['Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards',['../SubscriptionRevenue.html#sub_items_granted_method',1,'']]],
  ['track_20subscription_20billing_22',['Step 1: ReportSubscriptionRevenue - Track Subscription Billing',['../SubscriptionRevenue.html#sub_revenue_method',1,'']]],
  ['track_20the_20ad_20revenue_23',['ReportAdRevenue - Track the Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'']]],
  ['track_20the_20items_20delivered_24',['Step 2: ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['track_20the_20monetary_20transaction_25',['Step 1: ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['track_20tutorials_26',['Why Track Tutorials?',['../onboarding_milestone.html#rationale',1,'']]],
  ['tracking_27',['Tracking',['../AdRevenue.html#ad_methods',1,'Ad Revenue Tracking'],['../DummyGameIntegration.html#Scenario_10',1,'Scenario 10: Advanced Item &amp;amp; Goal Tracking'],['../DummyGameIntegration.html#Scenario_4',1,'Scenario 4: FTUE Milestones Tracking'],['../onboarding_milestone.html',1,'Tutorial Tracking']]],
  ['tracking_20ad_20offer_20acceptance_20rate_28',['Tracking Ad Offer Acceptance Rate',['../AdRevenue.html#ad_offer_tracking',1,'']]],
  ['tracking_20control_29',['Optional Button Click Tracking Control',['../QuickStart.html#ButtonClickControl',1,'']]],
  ['tracking_20in_20game_20windows_20and_20popups_30',['Tracking In-Game Windows and Popups',['../Windows.html#tracking-in-game-windows-and-popups',1,'']]],
  ['transaction_31',['Transaction',['../ItemExchange.html#Example2',1,'Player Loses a Broken Sword (One-Sided Transaction)'],['../ItemExchange.html#Example3',1,'Player Receives a Reward (One-Sided Transaction)'],['../InAppPurchases.html#iap_purchase',1,'Step 1: ReportInAppPurchase - Track the Monetary Transaction']]],
  ['trial_20period_32',['Scenario 2: Free Trial Period',['../SubscriptionRevenue.html#sub_scenario_trial',1,'']]],
  ['trip_20changes_20end_20of_20day_20settlement_33',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['trip_20day_3a_20reset_20mid_20trip_20changes_20end_20of_20day_20settlement_34',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['tutorial_20custom_20events_35',['Creating Tutorial Custom Events',['../onboarding_milestone.html#tutorial_creation',1,'']]],
  ['tutorial_20events_36',['Tutorial Events',['../onboarding_milestone.html#tutorial_multiple',1,'Creating Multiple Tutorial Events'],['../onboarding_milestone.html#tutorial_scenario',1,'When to Use Custom Tutorial Events']]],
  ['tutorial_20tracking_37',['Tutorial Tracking',['../onboarding_milestone.html',1,'']]],
  ['tutorials_38',['Tutorials',['../onboarding_milestone.html#tutorial_comparison',1,'FTUE vs Feature Tutorials'],['../onboarding_milestone.html#rationale',1,'Why Track Tutorials?']]],
  ['tutorials_20for_20advanced_20game_20features_39',['Tutorials for Advanced Game Features',['../onboarding_milestone.html#advanced_tutorials',1,'']]],
  ['two_20iap_20steps_40',['The Two IAP Steps',['../InAppPurchases.html#iap_methods',1,'']]],
  ['two_20steps_20separated_41',['Why Are These Two Steps Separated?',['../InAppPurchases.html#iap_why_separated',1,'']]],
  ['two_20subscription_20steps_42',['The Two Subscription Steps',['../SubscriptionRevenue.html#sub_methods',1,'']]],
  ['types_43',['Types',['../EventTypes.html#AutomaticEvents',1,'Automatic Event Types'],['../EventTypes.html',1,'Event Types'],['../EventTypes.html#ManualEvents',1,'Manual Event Types'],['../AdRevenue.html#ad_placement_context',1,'Use Game-Specific Context, Not Ad Types']]]
];
