var searchData=
[
  ['receives_20a_20reward_20one_20sided_20transaction_0',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['refill_1',['Scenario 2: Out of Energy - Watch to Refill',['../AdRevenue.html#ad_scenario_rewarded_energy',1,'']]],
  ['registration_20sign_20in_2',['Scenario 2: Player Registration &amp;amp; Sign-In',['../DummyGameIntegration.html#Scenario_2',1,'']]],
  ['renewal_3',['Scenario 3: Subscription Renewal',['../SubscriptionRevenue.html#sub_scenario_renewal',1,'']]],
  ['report_20actually_20granted_20items_4',['Report Actually Granted Items',['../InAppPurchases.html#iap_only_granted_items',1,'Only Report Actually Granted Items'],['../AdRevenue.html#ad_only_granted_items',1,'Only Report Actually Granted Items']]],
  ['report_20events_5',['Report Events',['../QuickStart.html#ReportEvents',1,'']]],
  ['report_20purchase_20once_20only_6',['Report Purchase Once Only',['../InAppPurchases.html#iap_report_once',1,'']]],
  ['reportabtestgroupassignment_7',['ReportABTestGroupAssignment',['../classKeewanoSDK.html#adcac900a769f4dddda9d65cc267a223f',1,'KeewanoSDK']]],
  ['reportaditemsgranted_8',['ReportAdItemsGranted',['../classKeewanoSDK.html#a742c5b095823cfab8656f1d9a68373ed',1,'KeewanoSDK.ReportAdItemsGranted(string placement, Item[] items)'],['../classKeewanoSDK.html#a812eb71ab26adfb35969c16689cd484f',1,'KeewanoSDK.ReportAdItemsGranted(string placement, ReadOnlySpan&lt; Keewano.Item &gt; items)']]],
  ['reportaditemsgranted_20for_20rewarded_20ads_9',['Only Call ReportAdItemsGranted for Rewarded Ads',['../AdRevenue.html#ad_only_rewarded_grants',1,'']]],
  ['reportaditemsgranted_20track_20rewarded_20ad_20items_10',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['reportadrevenue_11',['ReportAdRevenue',['../classKeewanoSDK.html#ad7a1cb7cf2ec193333b9f124bac94191',1,'KeewanoSDK.ReportAdRevenue(string placement, uint revenueUsdCents)'],['../classKeewanoSDK.html#ab84d2e991db6701dc32d77019110ab6a',1,'KeewanoSDK.ReportAdRevenue(string placement, float localizedRevenue, string currencyCode)']]],
  ['reportadrevenue_20track_20the_20ad_20revenue_12',['Step 1: ReportAdRevenue - Track the Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'']]],
  ['reportbuttonclick_13',['ReportButtonClick',['../classKeewanoSDK.html#a9944b568e714a66a4626f0bff69fe5bd',1,'KeewanoSDK']]],
  ['reportgamelanguage_14',['ReportGameLanguage',['../classKeewanoSDK.html#a3f3fd38d4d987900b2ec64ce196d5914',1,'KeewanoSDK']]],
  ['reportinapppurchase_15',['ReportInAppPurchase',['../classKeewanoSDK.html#a865cb9d89581de571b8e52f113661cec',1,'KeewanoSDK.ReportInAppPurchase(string productName, uint priceUsdCents)'],['../classKeewanoSDK.html#a801a5ef6d6baace50c0c4e0d76b1c2fe',1,'KeewanoSDK.ReportInAppPurchase(string productName, float localizedPrice, string currencyCode)']]],
  ['reportinapppurchase_20track_20the_20monetary_20transaction_16',['Step 1: ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['reportinapppurchaseitemsgranted_17',['ReportInAppPurchaseItemsGranted',['../classKeewanoSDK.html#a3ead93092535e6bf2eed29f7688c9632',1,'KeewanoSDK.ReportInAppPurchaseItemsGranted(string productName, Item[] items)'],['../classKeewanoSDK.html#a9516e661d72f9b563a5b0e4c0617b745',1,'KeewanoSDK.ReportInAppPurchaseItemsGranted(string productName, ReadOnlySpan&lt; Keewano.Item &gt; items)']]],
  ['reportinapppurchaseitemsgranted_20track_20the_20items_20delivered_18',['Step 2: ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['reporting_19',['Scenario 11: Custom Error Reporting',['../DummyGameIntegration.html#Scenario_11',1,'']]],
  ['reportinstallcampaign_20',['ReportInstallCampaign',['../classKeewanoSDK.html#ac3e1433b5be7b52e16886f9cc5e64cf5',1,'KeewanoSDK']]],
  ['reportitemsexchange_21',['ReportItemsExchange',['../classKeewanoSDK.html#a03af6ed00403dce0cad7dbcc44f88463',1,'KeewanoSDK.ReportItemsExchange(string exchangeLocation, Item[] from, Item[] to)'],['../classKeewanoSDK.html#a37d2e41f2089fd6693be14fd59e99391',1,'KeewanoSDK.ReportItemsExchange(string exchangeLocation, ReadOnlySpan&lt; Keewano.Item &gt; from, ReadOnlySpan&lt; Keewano.Item &gt; to)']]],
  ['reportitemsreset_22',['ReportItemsReset',['../classKeewanoSDK.html#a9e551800fbca5b7c84e61ac882fbe787',1,'KeewanoSDK']]],
  ['reportonboardingmilestone_23',['ReportOnboardingMilestone',['../classKeewanoSDK.html#ae478925a922b732056426e5a082c3e04',1,'KeewanoSDK.ReportOnboardingMilestone()'],['../onboarding_milestone.html#ftue_when',1,'When to Use ReportOnboardingMilestone']]],
  ['reportsubscriptionitemsgranted_24',['ReportSubscriptionItemsGranted',['../classKeewanoSDK.html#a9c131c279adc0fde06b7d0ce43a1c8b7',1,'KeewanoSDK.ReportSubscriptionItemsGranted(string packageName, Item[] items)'],['../classKeewanoSDK.html#adae26d6e430af4ec284b72ca9b21e936',1,'KeewanoSDK.ReportSubscriptionItemsGranted(string packageName, ReadOnlySpan&lt; Keewano.Item &gt; items)']]],
  ['reportsubscriptionitemsgranted_20track_20subscriber_20rewards_25',['Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards',['../SubscriptionRevenue.html#sub_items_granted_method',1,'']]],
  ['reportsubscriptionrevenue_26',['ReportSubscriptionRevenue',['../classKeewanoSDK.html#a6a855003c76a20fa7965c6a64bf50ca5',1,'KeewanoSDK.ReportSubscriptionRevenue(string packageName, uint revenueUsdCents)'],['../classKeewanoSDK.html#aa9a09d847c78a32816e8c94ea41d2d60',1,'KeewanoSDK.ReportSubscriptionRevenue(string packageName, float localizedRevenue, string currencyCode)']]],
  ['reportsubscriptionrevenue_20track_20subscription_20billing_27',['Step 1: ReportSubscriptionRevenue - Track Subscription Billing',['../SubscriptionRevenue.html#sub_revenue_method',1,'']]],
  ['reportwindowclose_28',['ReportWindowClose',['../classKeewanoSDK.html#a01e9a0872f73f6e758d6bb2b8182978b',1,'KeewanoSDK']]],
  ['reportwindowopen_29',['ReportWindowOpen',['../classKeewanoSDK.html#aca10811bff16611511be5b985c61dd0f',1,'KeewanoSDK']]],
  ['requirement_30',['Requirement',['../DataPrivacy.html#DP_configure',1,'Configuring Consent Requirement'],['../DataFormatSpecs.html#StringNonEmpty',1,'Non-Empty Requirement']]],
  ['reset_31',['Items Reset',['../ItemExchange.html#Items',1,'']]],
  ['reset_20by_20support_20team_32',['User Balance Fix Reset by Support Team',['../ItemExchange.html#Example6',1,'']]],
  ['reset_20mid_20trip_20changes_20end_20of_20day_20settlement_33',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['resets_34',['Scenario 8: Daily Resets',['../DummyGameIntegration.html#Scenario_8',1,'']]],
  ['revenue_35',['Revenue',['../AdRevenue.html',1,'Ad Revenue'],['../AdRevenue.html#ad_revenue_method',1,'Step 1: ReportAdRevenue - Track the Ad Revenue'],['../SubscriptionRevenue.html',1,'Subscription Revenue']]],
  ['revenue_20steps_36',['The Two Ad Revenue Steps',['../AdRevenue.html#ad_methods',1,'']]],
  ['revenue_20vs_20iap_37',['Ad Revenue vs IAP',['../AdRevenue.html#ad_distinction',1,'']]],
  ['reward_38',['Reward',['../AdRevenue.html#ad_scenario_interstitial',1,'Scenario 1: Interstitial Ad Between Levels (No Reward)'],['../AdRevenue.html#ad_scenario_daily_bonus',1,'Scenario 4: Daily Bonus - Watch to Double Reward'],['../AdRevenue.html#ad_scenario_banner',1,'Scenario 5: Main Menu Banner (No Reward)']]],
  ['reward_20one_20sided_20transaction_39',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['rewarded_20ad_20items_40',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['rewarded_20ads_41',['Only Call ReportAdItemsGranted for Rewarded Ads',['../AdRevenue.html#ad_only_rewarded_grants',1,'']]],
  ['rewards_42',['Rewards',['../SubscriptionRevenue.html#sub_scenario_daily',1,'Scenario 4: Daily Subscriber Rewards'],['../SubscriptionRevenue.html#sub_scenario_multiple',1,'Scenario 5: Multiple Item Rewards'],['../AdRevenue.html#ad_scenario_multiple_items',1,'Scenario 7: Multiple Item Rewards'],['../SubscriptionRevenue.html#sub_items_granted_method',1,'Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards']]],
  ['road_20trip_20day_3a_20reset_20mid_20trip_20changes_20end_20of_20day_20settlement_43',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]]
];
