var searchData=
[
  ['call_20early_0',['Call Early',['../ExistingGameIntegration.html#existing_bp_early',1,'']]],
  ['call_20for_20new_20users_1',['Don&apos;t Call for New Users',['../ExistingGameIntegration.html#existing_warn_new_users',1,'']]],
  ['call_20reportaditemsgranted_20when_20items_20are_20granted_2',['Only Call ReportAdItemsGranted When Items Are Granted',['../AdRevenue.html#ad_only_when_granted',1,'']]],
  ['callbacks_3',['Always Use Ad Network Callbacks',['../AdRevenue.html#ad_use_callbacks',1,'']]],
  ['campaign_4',['Marketing Campaign',['../install_campaign.html',1,'']]],
  ['card_5',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['cases_6',['Use Cases',['../install_campaign.html#campaign_use_cases',1,'']]],
  ['cases_20for_20separation_7',['Common Cases for Separation',['../InAppPurchases.html#iap_separation_reasons',1,'']]],
  ['changes_20end_20of_20day_20settlement_8',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['changing_20language_9',['Scenario 3: Entering Main Menu &amp;amp; Changing Language',['../DummyGameIntegration.html#Scenario_3',1,'']]],
  ['click_20tracking_20control_10',['Optional Button Click Tracking Control',['../QuickStart.html#ButtonClickControl',1,'']]],
  ['coffee_20shop_3a_20pay_20with_20voucher_20or_20credits_20stamp_20card_11',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['coins_12',['Scenario 6: Shop - Watch for Free Coins',['../AdRevenue.html#ad_scenario_shop',1,'']]],
  ['coins_20and_20a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_13',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['combat_20power_20ups_14',['Scenario 6: In-Game Combat &amp;amp; Power-Ups',['../DummyGameIntegration.html#Scenario_6',1,'']]],
  ['common_20cases_20for_20separation_15',['Common Cases for Separation',['../InAppPurchases.html#iap_separation_reasons',1,'']]],
  ['common_20mistakes_16',['Common Mistakes',['../ExistingGameIntegration.html#existing_warnings',1,'']]],
  ['common_20scenarios_17',['Common Scenarios',['../InAppPurchases.html#iap_scenarios',1,'Common Scenarios'],['../AdRevenue.html#ad_scenarios',1,'Common Scenarios'],['../SubscriptionRevenue.html#sub_scenarios',1,'Common Scenarios']]],
  ['complete_20purchase_20flow_18',['The Complete Purchase Flow',['../InAppPurchases.html#iap_flow',1,'']]],
  ['completion_19',['Scenario 5: Level Start &amp;amp; Completion',['../DummyGameIntegration.html#Scenario_5',1,'']]],
  ['compliance_20',['Compliance',['../DataPrivacy.html#DP_default',1,'Default Privacy Compliance'],['../QuickStart.html#Default',1,'Privacy Compliance']]],
  ['concept_3a_20context_20first_20events_21',['Key Concept: Context-First Events',['../DummyGameIntegration.html#ConceptShift',1,'']]],
  ['configure_20your_20project_22',['Configure your Project',['../QuickStart.html#Configure',1,'']]],
  ['configuring_20consent_20requirement_23',['Configuring Consent Requirement',['../DataPrivacy.html#DP_configure',1,'']]],
  ['conflicts_24',['Merge Conflicts',['../CustomEventsPage.html#custom_events_merge_conflicts',1,'']]],
  ['consent_25',['Consent',['../DataPrivacy.html#DP_consent',1,'Optional User Consent'],['../DummyGameIntegration.html#Scenario_1',1,'Scenario 1: First Launch &amp;amp; Consent'],['../QuickStart.html#Optional',1,'User Consent']]],
  ['consent_20requirement_26',['Configuring Consent Requirement',['../DataPrivacy.html#DP_configure',1,'']]],
  ['consistent_20package_20names_27',['Use Consistent Package Names',['../SubscriptionRevenue.html#sub_consistent_package',1,'']]],
  ['consistent_20placement_20names_28',['Use Consistent Placement Names',['../AdRevenue.html#ad_consistent_placement',1,'']]],
  ['consistent_20product_20ids_29',['Use Consistent Product IDs',['../InAppPurchases.html#iap_product_ids',1,'']]],
  ['context_20first_20events_30',['Key Concept: Context-First Events',['../DummyGameIntegration.html#ConceptShift',1,'']]],
  ['context_20matters_31',['Why Context Matters',['../AdRevenue.html#ad_placement_rationale',1,'']]],
  ['context_20not_20ad_20types_32',['Use Game-Specific Context, Not Ad Types',['../AdRevenue.html#ad_placement_context',1,'']]],
  ['control_33',['Optional Button Click Tracking Control',['../QuickStart.html#ButtonClickControl',1,'']]],
  ['count_34',['Count',['../structKeewano_1_1Item.html#a68f5ac73f138b41748ff8bd4f9a8ba67',1,'Keewano::Item']]],
  ['creating_20multiple_20tutorial_20events_35',['Creating Multiple Tutorial Events',['../onboarding_milestone.html#tutorial_multiple',1,'']]],
  ['creating_20tutorial_20custom_20events_36',['Creating Tutorial Custom Events',['../onboarding_milestone.html#tutorial_creation',1,'']]],
  ['credits_20stamp_20card_37',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['critical_38',['Server Validation is Critical',['../InAppPurchases.html#iap_validation_critical',1,'']]],
  ['custom_20error_20reporting_39',['Scenario 11: Custom Error Reporting',['../DummyGameIntegration.html#Scenario_11',1,'']]],
  ['custom_20events_40',['Custom Events',['../CustomEventsPage.html#custom_events_adding',1,'Adding Custom Events'],['../onboarding_milestone.html#tutorial_creation',1,'Creating Tutorial Custom Events'],['../CustomEventsPage.html',1,'Custom Events'],['../EventTypes.html#CustomEventsSection',1,'Custom Events']]],
  ['custom_20tutorial_20events_41',['When to Use Custom Tutorial Events',['../onboarding_milestone.html#tutorial_scenario',1,'']]]
];
