var searchData=
[
  ['rate_0',['Tracking Ad Offer Acceptance Rate',['../AdRevenue.html#ad_offer_tracking',1,'']]],
  ['receives_20a_20reward_20one_20sided_20transaction_1',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['recommended_20integration_20flow_2',['Recommended Integration Flow',['../ExistingGameIntegration.html#existing_usage_flow',1,'']]],
  ['refill_3',['Scenario 2: Out of Energy - Watch to Refill',['../AdRevenue.html#ad_scenario_rewarded_energy',1,'']]],
  ['registration_20sign_20in_4',['Scenario 2: Player Registration &amp;amp; Sign-In',['../DummyGameIntegration.html#Scenario_2',1,'']]],
  ['renewal_5',['Scenario 3: Subscription Renewal',['../SubscriptionRevenue.html#sub_scenario_renewal',1,'']]],
  ['report_20actually_20granted_20items_6',['Report Actually Granted Items',['../InAppPurchases.html#iap_only_granted_items',1,'Only Report Actually Granted Items'],['../AdRevenue.html#ad_only_granted_items',1,'Only Report Actually Granted Items']]],
  ['report_20events_7',['Report Events',['../QuickStart.html#ReportEvents',1,'']]],
  ['report_20purchase_20once_20only_8',['Report Purchase Once Only',['../InAppPurchases.html#iap_report_once',1,'']]],
  ['reportabtestgroupassignment_9',['ReportABTestGroupAssignment',['../classKeewanoSDK.html#adcac900a769f4dddda9d65cc267a223f',1,'KeewanoSDK']]],
  ['reportaditemsgranted_10',['ReportAdItemsGranted',['../classKeewanoSDK.html#a742c5b095823cfab8656f1d9a68373ed',1,'KeewanoSDK.ReportAdItemsGranted(string placement, Item[] items)'],['../classKeewanoSDK.html#a812eb71ab26adfb35969c16689cd484f',1,'KeewanoSDK.ReportAdItemsGranted(string placement, ReadOnlySpan&lt; Keewano.Item &gt; items)']]],
  ['reportaditemsgranted_20track_20rewarded_20ad_20items_11',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['reportaditemsgranted_20when_20items_20are_20granted_12',['Only Call ReportAdItemsGranted When Items Are Granted',['../AdRevenue.html#ad_only_when_granted',1,'']]],
  ['reportadoffered_13',['ReportAdOffered',['../classKeewanoSDK.html#a0503b0da2dbf0670136aa3630b477e90',1,'KeewanoSDK']]],
  ['reportadrevenue_14',['ReportAdRevenue',['../classKeewanoSDK.html#ad7a1cb7cf2ec193333b9f124bac94191',1,'KeewanoSDK.ReportAdRevenue(string placement, uint revenueUsdCents)'],['../classKeewanoSDK.html#ab84d2e991db6701dc32d77019110ab6a',1,'KeewanoSDK.ReportAdRevenue(string placement, float localizedRevenue, string currencyCode)']]],
  ['reportadrevenue_20track_20the_20ad_20revenue_15',['ReportAdRevenue - Track the Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'']]],
  ['reportbuttonclick_16',['ReportButtonClick',['../classKeewanoSDK.html#a9944b568e714a66a4626f0bff69fe5bd',1,'KeewanoSDK']]],
  ['reportgamelanguage_17',['ReportGameLanguage',['../classKeewanoSDK.html#a3f3fd38d4d987900b2ec64ce196d5914',1,'KeewanoSDK']]],
  ['reportinapppurchase_18',['ReportInAppPurchase',['../classKeewanoSDK.html#a865cb9d89581de571b8e52f113661cec',1,'KeewanoSDK.ReportInAppPurchase(string productName, uint priceUsdCents)'],['../classKeewanoSDK.html#a801a5ef6d6baace50c0c4e0d76b1c2fe',1,'KeewanoSDK.ReportInAppPurchase(string productName, float localizedPrice, string currencyCode)']]],
  ['reportinapppurchase_20track_20the_20monetary_20transaction_19',['Step 1: ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['reportinapppurchaseitemsgranted_20',['ReportInAppPurchaseItemsGranted',['../classKeewanoSDK.html#a3ead93092535e6bf2eed29f7688c9632',1,'KeewanoSDK.ReportInAppPurchaseItemsGranted(string productName, Item[] items)'],['../classKeewanoSDK.html#a9516e661d72f9b563a5b0e4c0617b745',1,'KeewanoSDK.ReportInAppPurchaseItemsGranted(string productName, ReadOnlySpan&lt; Keewano.Item &gt; items)']]],
  ['reportinapppurchaseitemsgranted_20track_20the_20items_20delivered_21',['Step 2: ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['reporting_22',['Scenario 11: Custom Error Reporting',['../DummyGameIntegration.html#Scenario_11',1,'']]],
  ['reportinstallcampaign_23',['ReportInstallCampaign',['../classKeewanoSDK.html#ac3e1433b5be7b52e16886f9cc5e64cf5',1,'KeewanoSDK']]],
  ['reportitemsexchange_24',['ReportItemsExchange',['../classKeewanoSDK.html#a03af6ed00403dce0cad7dbcc44f88463',1,'KeewanoSDK.ReportItemsExchange(string exchangeLocation, Item[] from, Item[] to)'],['../classKeewanoSDK.html#a37d2e41f2089fd6693be14fd59e99391',1,'KeewanoSDK.ReportItemsExchange(string exchangeLocation, ReadOnlySpan&lt; Keewano.Item &gt; from, ReadOnlySpan&lt; Keewano.Item &gt; to)']]],
  ['reportitemsreset_25',['ReportItemsReset',['../classKeewanoSDK.html#a9e551800fbca5b7c84e61ac882fbe787',1,'KeewanoSDK']]],
  ['reportonboardingmilestone_26',['ReportOnboardingMilestone',['../classKeewanoSDK.html#ae478925a922b732056426e5a082c3e04',1,'KeewanoSDK.ReportOnboardingMilestone()'],['../onboarding_milestone.html#ftue_when',1,'When to Use ReportOnboardingMilestone']]],
  ['reportsubscriptionitemsgranted_27',['ReportSubscriptionItemsGranted',['../classKeewanoSDK.html#a9c131c279adc0fde06b7d0ce43a1c8b7',1,'KeewanoSDK.ReportSubscriptionItemsGranted(string packageName, Item[] items)'],['../classKeewanoSDK.html#adae26d6e430af4ec284b72ca9b21e936',1,'KeewanoSDK.ReportSubscriptionItemsGranted(string packageName, ReadOnlySpan&lt; Keewano.Item &gt; items)']]],
  ['reportsubscriptionitemsgranted_20track_20subscriber_20rewards_28',['Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards',['../SubscriptionRevenue.html#sub_items_granted_method',1,'']]],
  ['reportsubscriptionrevenue_29',['ReportSubscriptionRevenue',['../classKeewanoSDK.html#a6a855003c76a20fa7965c6a64bf50ca5',1,'KeewanoSDK.ReportSubscriptionRevenue(string packageName, uint revenueUsdCents)'],['../classKeewanoSDK.html#aa9a09d847c78a32816e8c94ea41d2d60',1,'KeewanoSDK.ReportSubscriptionRevenue(string packageName, float localizedRevenue, string currencyCode)']]],
  ['reportsubscriptionrevenue_20track_20subscription_20billing_30',['Step 1: ReportSubscriptionRevenue - Track Subscription Billing',['../SubscriptionRevenue.html#sub_revenue_method',1,'']]],
  ['reportuserregisteredbeforesdkintegration_31',['ReportUserRegisteredBeforeSDKIntegration',['../classKeewanoSDK.html#a6f01138d37dc29d65eeee89aaa32cd1b',1,'KeewanoSDK']]],
  ['reportwindowclose_32',['ReportWindowClose',['../classKeewanoSDK.html#a01e9a0872f73f6e758d6bb2b8182978b',1,'KeewanoSDK']]],
  ['reportwindowopen_33',['ReportWindowOpen',['../classKeewanoSDK.html#aca10811bff16611511be5b985c61dd0f',1,'KeewanoSDK']]],
  ['requirement_34',['Requirement',['../DataPrivacy.html#DP_configure',1,'Configuring Consent Requirement'],['../DataFormatSpecs.html#StringNonEmpty',1,'Non-Empty Requirement']]],
  ['reset_35',['Items Reset',['../ItemExchange.html#Items',1,'']]],
  ['reset_20by_20support_20team_36',['User Balance Fix Reset by Support Team',['../ItemExchange.html#Example6',1,'']]],
  ['reset_20mid_20trip_20changes_20end_20of_20day_20settlement_37',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['resets_38',['Scenario 8: Daily Resets',['../DummyGameIntegration.html#Scenario_8',1,'']]],
  ['revenue_39',['Revenue',['../AdRevenue.html',1,'Ad Revenue'],['../AdRevenue.html#ad_revenue_method',1,'ReportAdRevenue - Track the Ad Revenue'],['../SubscriptionRevenue.html',1,'Subscription Revenue']]],
  ['revenue_20and_20item_20grants_20separate_40',['Why Are Revenue and Item Grants Separate?',['../AdRevenue.html#ad_why_separated',1,'']]],
  ['revenue_20tracking_41',['Ad Revenue Tracking',['../AdRevenue.html#ad_methods',1,'']]],
  ['revenue_20vs_20iap_42',['Ad Revenue vs IAP',['../AdRevenue.html#ad_distinction',1,'']]],
  ['reward_43',['Reward',['../AdRevenue.html#ad_scenario_interstitial',1,'Scenario 1: Interstitial Ad Between Levels (No Reward)'],['../AdRevenue.html#ad_scenario_daily_bonus',1,'Scenario 4: Daily Bonus - Watch to Double Reward'],['../AdRevenue.html#ad_scenario_banner',1,'Scenario 5: Main Menu Banner (No Reward)']]],
  ['reward_20one_20sided_20transaction_44',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['rewarded_45',['Rewarded',['../namespaceKeewano.html#afdfeb6f81f95f7adfbfb52086bc63014ab344d16193a2cd3a64dbbf73e05bc4bc',1,'Keewano']]],
  ['rewarded_20ad_20items_46',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['rewards_47',['Rewards',['../SubscriptionRevenue.html#sub_scenario_daily',1,'Scenario 4: Daily Subscriber Rewards'],['../SubscriptionRevenue.html#sub_scenario_multiple',1,'Scenario 5: Multiple Item Rewards'],['../AdRevenue.html#ad_scenario_multiple_items',1,'Scenario 7: Multiple Item Rewards'],['../SubscriptionRevenue.html#sub_items_granted_method',1,'Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards']]],
  ['road_20trip_20day_3a_20reset_20mid_20trip_20changes_20end_20of_20day_20settlement_48',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]]
];
