var searchData=
[
  ['iap_0',['IAP',['../AdRevenue.html#ad_distinction',1,'Ad Revenue vs IAP'],['../DummyGameIntegration.html#Scenario_7',1,'Scenario 7: Store Purchases (IAP)']]],
  ['iap_20steps_1',['The Two IAP Steps',['../InAppPurchases.html#iap_methods',1,'']]],
  ['iap_20vs_20virtual_20economy_2',['IAP vs Virtual Economy',['../InAppPurchases.html#iap_distinction',1,'']]],
  ['identify_20items_20across_20all_20apis_3',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['identify_20users_4',['Identify Users',['../QuickStart.html#UserId',1,'']]],
  ['ideology_5',['Performance-First Ideology',['../index.html#performance-first-ideology',1,'']]],
  ['ids_6',['Use Consistent Product IDs',['../InAppPurchases.html#iap_product_ids',1,'']]],
  ['immediate_20grant_20synchronous_7',['Scenario 1: Immediate Grant (Synchronous)',['../InAppPurchases.html#iap_scenario_immediate',1,'']]],
  ['in_8',['Scenario 2: Player Registration &amp;amp; Sign-In',['../DummyGameIntegration.html#Scenario_2',1,'']]],
  ['in_20app_20purchases_9',['In-App Purchases',['../InAppPurchases.html',1,'']]],
  ['in_20game_20balance_10',['In-Game Balance',['../ItemExchange.html',1,'']]],
  ['in_20game_20combat_20power_20ups_11',['Scenario 6: In-Game Combat &amp;amp; Power-Ups',['../DummyGameIntegration.html#Scenario_6',1,'']]],
  ['in_20game_20windows_20and_20popups_12',['Tracking In-Game Windows and Popups',['../Windows.html#tracking-in-game-windows-and-popups',1,'']]],
  ['initial_20subscription_20purchase_13',['Scenario 1: Initial Subscription Purchase',['../SubscriptionRevenue.html#sub_scenario_initial',1,'']]],
  ['installation_14',['Installation',['../QuickStart.html#Install',1,'Installation'],['../ExistingGameIntegration.html#existing_behavior_once',1,'Once Per Installation']]],
  ['integrating_20into_20existing_20games_15',['Integrating into Existing Games',['../QuickStart.html#ExistingGame',1,'']]],
  ['integrating_20sdk_20into_20existing_20games_16',['Integrating SDK into Existing Games',['../ExistingGameIntegration.html',1,'']]],
  ['integration_17',['Integration',['../ExistingGameIntegration.html#existing_simple',1,'Simple Integration'],['../DummyGameIntegration.html',1,'Step-by-Step Example Integration']]],
  ['integration_20flow_18',['Recommended Integration Flow',['../ExistingGameIntegration.html#existing_usage_flow',1,'']]],
  ['integration_20scenarios_19',['Integration Scenarios',['../DummyGameIntegration.html#IntegrationScenarios',1,'']]],
  ['integration_20testing_20',['SDK Integration Testing',['../IntegrationTesting.html',1,'']]],
  ['interstitial_20ad_20between_20levels_20no_20reward_21',['Scenario 1: Interstitial Ad Between Levels (No Reward)',['../AdRevenue.html#ad_scenario_interstitial',1,'']]],
  ['into_20existing_20games_22',['into Existing Games',['../QuickStart.html#ExistingGame',1,'Integrating into Existing Games'],['../ExistingGameIntegration.html',1,'Integrating SDK into Existing Games']]],
  ['is_20critical_23',['Server Validation is Critical',['../InAppPurchases.html#iap_validation_critical',1,'']]],
  ['is_20never_20lost_24',['Your Data is Never Lost',['../OfflineAnalytics.html#OfflineOverview',1,'']]],
  ['it_20works_25',['How It Works',['../OfflineAnalytics.html#OfflineHow',1,'']]],
  ['item_26',['Defining an &quot;Item&quot;',['../ItemExchange.html#ItemConcept',1,'']]],
  ['item_20goal_20tracking_27',['Scenario 10: Advanced Item &amp;amp; Goal Tracking',['../DummyGameIntegration.html#Scenario_10',1,'']]],
  ['item_20grants_20separate_28',['Why Are Revenue and Item Grants Separate?',['../AdRevenue.html#ad_why_separated',1,'']]],
  ['item_20names_20identify_20items_20across_20all_20apis_29',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['item_20rewards_30',['Item Rewards',['../SubscriptionRevenue.html#sub_scenario_multiple',1,'Scenario 5: Multiple Item Rewards'],['../AdRevenue.html#ad_scenario_multiple_items',1,'Scenario 7: Multiple Item Rewards']]],
  ['items_31',['Items',['../InAppPurchases.html#iap_only_granted_items',1,'Only Report Actually Granted Items'],['../AdRevenue.html#ad_only_granted_items',1,'Only Report Actually Granted Items'],['../InAppPurchases.html#iap_scenario_bundle',1,'Scenario 4: Bundle with Multiple Items'],['../AdRevenue.html#ad_items_granted_method',1,'Step 2: ReportAdItemsGranted - Track Rewarded Ad Items']]],
  ['items_20across_20all_20apis_32',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['items_20are_20granted_33',['Only Call ReportAdItemsGranted When Items Are Granted',['../AdRevenue.html#ad_only_when_granted',1,'']]],
  ['items_20delivered_34',['Step 2: ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['items_20exchange_35',['Items Exchange',['../ItemExchange.html#Exchange',1,'']]],
  ['items_20reset_36',['Items Reset',['../ItemExchange.html#Items',1,'']]]
];
