var searchData=
[
  ['receives_20a_20reward_20one_20sided_20transaction_0',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['refill_1',['Scenario 2: Out of Energy - Watch to Refill',['../AdRevenue.html#ad_scenario_rewarded_energy',1,'']]],
  ['registration_20sign_20in_2',['Scenario 2: Player Registration &amp;amp; Sign-In',['../DummyGameIntegration.html#Scenario_2',1,'']]],
  ['renewal_3',['Scenario 3: Subscription Renewal',['../SubscriptionRevenue.html#sub_scenario_renewal',1,'']]],
  ['report_20actually_20granted_20items_4',['Report Actually Granted Items',['../InAppPurchases.html#iap_only_granted_items',1,'Only Report Actually Granted Items'],['../AdRevenue.html#ad_only_granted_items',1,'Only Report Actually Granted Items']]],
  ['report_20events_5',['Report Events',['../QuickStart.html#ReportEvents',1,'']]],
  ['report_20purchase_20once_20only_6',['Report Purchase Once Only',['../InAppPurchases.html#iap_report_once',1,'']]],
  ['reportaditemsgranted_20for_20rewarded_20ads_7',['Only Call ReportAdItemsGranted for Rewarded Ads',['../AdRevenue.html#ad_only_rewarded_grants',1,'']]],
  ['reportaditemsgranted_20track_20rewarded_20ad_20items_8',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['reportadrevenue_20track_20the_20ad_20revenue_9',['Step 1: ReportAdRevenue - Track the Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'']]],
  ['reportinapppurchase_20track_20the_20monetary_20transaction_10',['Step 1: ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['reportinapppurchaseitemsgranted_20track_20the_20items_20delivered_11',['Step 2: ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['reporting_12',['Scenario 11: Custom Error Reporting',['../DummyGameIntegration.html#Scenario_11',1,'']]],
  ['reportonboardingmilestone_13',['When to Use ReportOnboardingMilestone',['../onboarding_milestone.html#ftue_when',1,'']]],
  ['reportsubscriptionitemsgranted_20track_20subscriber_20rewards_14',['Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards',['../SubscriptionRevenue.html#sub_items_granted_method',1,'']]],
  ['reportsubscriptionrevenue_20track_20subscription_20billing_15',['Step 1: ReportSubscriptionRevenue - Track Subscription Billing',['../SubscriptionRevenue.html#sub_revenue_method',1,'']]],
  ['requirement_16',['Requirement',['../DataPrivacy.html#DP_configure',1,'Configuring Consent Requirement'],['../DataFormatSpecs.html#StringNonEmpty',1,'Non-Empty Requirement']]],
  ['reset_17',['Items Reset',['../ItemExchange.html#Items',1,'']]],
  ['reset_20by_20support_20team_18',['User Balance Fix Reset by Support Team',['../ItemExchange.html#Example6',1,'']]],
  ['reset_20mid_20trip_20changes_20end_20of_20day_20settlement_19',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['resets_20',['Scenario 8: Daily Resets',['../DummyGameIntegration.html#Scenario_8',1,'']]],
  ['revenue_21',['Revenue',['../AdRevenue.html',1,'Ad Revenue'],['../AdRevenue.html#ad_revenue_method',1,'Step 1: ReportAdRevenue - Track the Ad Revenue'],['../SubscriptionRevenue.html',1,'Subscription Revenue']]],
  ['revenue_20steps_22',['The Two Ad Revenue Steps',['../AdRevenue.html#ad_methods',1,'']]],
  ['revenue_20vs_20iap_23',['Ad Revenue vs IAP',['../AdRevenue.html#ad_distinction',1,'']]],
  ['reward_24',['Reward',['../AdRevenue.html#ad_scenario_interstitial',1,'Scenario 1: Interstitial Ad Between Levels (No Reward)'],['../AdRevenue.html#ad_scenario_daily_bonus',1,'Scenario 4: Daily Bonus - Watch to Double Reward'],['../AdRevenue.html#ad_scenario_banner',1,'Scenario 5: Main Menu Banner (No Reward)']]],
  ['reward_20one_20sided_20transaction_25',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['rewarded_20ad_20items_26',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['rewarded_20ads_27',['Only Call ReportAdItemsGranted for Rewarded Ads',['../AdRevenue.html#ad_only_rewarded_grants',1,'']]],
  ['rewards_28',['Rewards',['../SubscriptionRevenue.html#sub_scenario_daily',1,'Scenario 4: Daily Subscriber Rewards'],['../SubscriptionRevenue.html#sub_scenario_multiple',1,'Scenario 5: Multiple Item Rewards'],['../AdRevenue.html#ad_scenario_multiple_items',1,'Scenario 7: Multiple Item Rewards'],['../SubscriptionRevenue.html#sub_items_granted_method',1,'Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards']]],
  ['road_20trip_20day_3a_20reset_20mid_20trip_20changes_20end_20of_20day_20settlement_29',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]]
];
