var searchData=
[
  ['a_20broken_20sword_20one_20sided_20transaction_0',['Player Loses a Broken Sword (One-Sided Transaction)',['../ItemExchange.html#Example2',1,'']]],
  ['a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_1',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['a_20reward_20one_20sided_20transaction_2',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['across_20all_20apis_3',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['actually_20granted_20items_4',['Actually Granted Items',['../InAppPurchases.html#iap_only_granted_items',1,'Only Report Actually Granted Items'],['../AdRevenue.html#ad_only_granted_items',1,'Only Report Actually Granted Items']]],
  ['ad_20between_20levels_20no_20reward_5',['Scenario 1: Interstitial Ad Between Levels (No Reward)',['../AdRevenue.html#ad_scenario_interstitial',1,'']]],
  ['ad_20items_6',['2. ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['ad_20network_20callbacks_7',['Always Use Ad Network Callbacks',['../AdRevenue.html#ad_use_callbacks',1,'']]],
  ['ad_20revenue_8',['Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'1. ReportAdRevenue - Track the Ad Revenue'],['../AdRevenue.html',1,'Ad Revenue']]],
  ['ad_20revenue_20methods_9',['The Two Ad Revenue Methods',['../AdRevenue.html#ad_methods',1,'']]],
  ['ad_20revenue_20vs_20iap_10',['Ad Revenue vs IAP',['../AdRevenue.html#ad_distinction',1,'']]],
  ['ad_20types_11',['Use Game-Specific Context, Not Ad Types',['../AdRevenue.html#ad_placement_context',1,'']]],
  ['adding_20custom_20events_12',['Adding Custom Events',['../CustomEventsPage.html#custom_events_adding',1,'']]],
  ['ads_13',['Only Call ReportAdItemsGranted for Rewarded Ads',['../AdRevenue.html#ad_only_rewarded_grants',1,'']]],
  ['advanced_20game_20features_14',['Tutorials for Advanced Game Features',['../onboarding_milestone.html#advanced_tutorials',1,'']]],
  ['advanced_20item_20goal_20tracking_15',['Scenario 10: Advanced Item &amp;amp; Goal Tracking',['../DummyGameIntegration.html#Scenario_10',1,'']]],
  ['all_20apis_16',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['also_17',['Also',['../InAppPurchases.html#iap_see_also',1,'See Also'],['../AdRevenue.html#ad_see_also',1,'See Also'],['../SubscriptionRevenue.html#sub_see_also',1,'See Also']]],
  ['always_20use_20ad_20network_20callbacks_18',['Always Use Ad Network Callbacks',['../AdRevenue.html#ad_use_callbacks',1,'']]],
  ['an_20item_19',['Defining an &quot;Item&quot;',['../ItemExchange.html#ItemConcept',1,'']]],
  ['analytics_20',['Offline Analytics',['../OfflineAnalytics.html',1,'']]],
  ['and_20a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_21',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['and_20popups_22',['and Popups',['../Windows.html#tracking-in-game-windows-and-popups',1,'Tracking In-Game Windows and Popups'],['../Windows.html',1,'Windows and Popups']]],
  ['apis_23',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['app_20purchases_24',['In-App Purchases',['../InAppPurchases.html',1,'']]],
  ['are_20built_25',['How Funnels Are Built',['../onboarding_milestone.html#ftue_funnel',1,'']]],
  ['are_20these_20two_20methods_20separated_26',['Are These Two Methods Separated',['../InAppPurchases.html#iap_why_separated',1,'Why Are These Two Methods Separated?'],['../AdRevenue.html#ad_why_separated',1,'Why Are These Two Methods Separated?']]],
  ['asynchronous_27',['Scenario 2: Delayed Grant (Asynchronous)',['../InAppPurchases.html#iap_scenario_delayed',1,'']]],
  ['automatic_20event_20types_28',['Automatic Event Types',['../EventTypes.html#AutomaticEvents',1,'']]]
];
