var searchData=
[
  ['main_20menu_20banner_20no_20reward_0',['Scenario 5: Main Menu Banner (No Reward)',['../AdRevenue.html#ad_scenario_banner',1,'']]],
  ['main_20menu_20changing_20language_1',['Scenario 3: Entering Main Menu &amp;amp; Changing Language',['../DummyGameIntegration.html#Scenario_3',1,'']]],
  ['manual_20event_20types_2',['Manual Event Types',['../EventTypes.html#ManualEvents',1,'']]],
  ['marketing_20campaign_3',['Marketing Campaign',['../install_campaign.html',1,'']]],
  ['match3_20level_20scenario_4',['Match3 Level Scenario',['../ItemExchange.html#Example4',1,'']]],
  ['matters_5',['Why Context Matters',['../AdRevenue.html#ad_placement_rationale',1,'']]],
  ['maximum_20length_6',['Maximum Length',['../DataFormatSpecs.html#StringLength',1,'']]],
  ['menu_20banner_20no_20reward_7',['Scenario 5: Main Menu Banner (No Reward)',['../AdRevenue.html#ad_scenario_banner',1,'']]],
  ['menu_20changing_20language_8',['Scenario 3: Entering Main Menu &amp;amp; Changing Language',['../DummyGameIntegration.html#Scenario_3',1,'']]],
  ['merge_20conflicts_9',['Merge Conflicts',['../CustomEventsPage.html#custom_events_merge_conflicts',1,'']]],
  ['method_10',['SetUserConsent Method',['../DataPrivacy.html#DP_method',1,'']]],
  ['methods_11',['Methods',['../AdRevenue.html#ad_methods',1,'The Two Ad Revenue Methods'],['../InAppPurchases.html#iap_methods',1,'The Two IAP Methods'],['../SubscriptionRevenue.html#sub_methods',1,'The Two Subscription Methods']]],
  ['methods_20separated_12',['Methods Separated',['../InAppPurchases.html#iap_why_separated',1,'Why Are These Two Methods Separated?'],['../AdRevenue.html#ad_why_separated',1,'Why Are These Two Methods Separated?']]],
  ['mid_20trip_20changes_20end_20of_20day_20settlement_13',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['milestones_20tracking_14',['Scenario 4: FTUE Milestones Tracking',['../DummyGameIntegration.html#Scenario_4',1,'']]],
  ['monetary_20transaction_15',['1. ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['monthly_20daily_20packages_16',['Scenario 3: Monthly/Daily Packages',['../InAppPurchases.html#iap_scenario_monthly',1,'']]],
  ['monthly_20login_20package_17',['Example: Monthly Login Package',['../InAppPurchases.html#iap_separation_example',1,'']]],
  ['moves_18',['Scenario 3: Level Failed - Watch for Extra Moves',['../AdRevenue.html#ad_scenario_level_failed',1,'']]],
  ['multiple_20item_20rewards_19',['Multiple Item Rewards',['../SubscriptionRevenue.html#sub_scenario_multiple',1,'Scenario 5: Multiple Item Rewards'],['../AdRevenue.html#ad_scenario_multiple_items',1,'Scenario 7: Multiple Item Rewards']]],
  ['multiple_20items_20',['Scenario 4: Bundle with Multiple Items',['../InAppPurchases.html#iap_scenario_bundle',1,'']]],
  ['multiple_20tutorial_20events_21',['Creating Multiple Tutorial Events',['../onboarding_milestone.html#tutorial_multiple',1,'']]],
  ['must_20be_20in_20usd_20cents_22',['Must Be in USD Cents',['../InAppPurchases.html#iap_price_usd',1,'Prices Must Be in USD Cents'],['../AdRevenue.html#ad_revenue_usd',1,'Revenue Must Be in USD Cents'],['../SubscriptionRevenue.html#sub_revenue_usd',1,'Revenue Must Be in USD Cents']]]
];
