var searchData=
[
  ['call_20reportaditemsgranted_20for_20rewarded_20ads_0',['Only Call ReportAdItemsGranted for Rewarded Ads',['../AdRevenue.html#ad_only_rewarded_grants',1,'']]],
  ['callbacks_1',['Always Use Ad Network Callbacks',['../AdRevenue.html#ad_use_callbacks',1,'']]],
  ['campaign_2',['Marketing Campaign',['../install_campaign.html',1,'']]],
  ['card_3',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['cases_4',['Cases',['../AdRevenue.html#ad_separation_reasons',1,'Common Cases'],['../install_campaign.html#campaign_use_cases',1,'Use Cases']]],
  ['cases_20for_20separation_5',['Common Cases for Separation',['../InAppPurchases.html#iap_separation_reasons',1,'']]],
  ['changes_20end_20of_20day_20settlement_6',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['changing_20language_7',['Scenario 3: Entering Main Menu &amp;amp; Changing Language',['../DummyGameIntegration.html#Scenario_3',1,'']]],
  ['click_20tracking_20control_8',['Optional Button Click Tracking Control',['../QuickStart.html#ButtonClickControl',1,'']]],
  ['coffee_20shop_3a_20pay_20with_20voucher_20or_20credits_20stamp_20card_9',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['coins_10',['Scenario 6: Shop - Watch for Free Coins',['../AdRevenue.html#ad_scenario_shop',1,'']]],
  ['coins_20and_20a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_11',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['combat_20power_20ups_12',['Scenario 6: In-Game Combat &amp;amp; Power-Ups',['../DummyGameIntegration.html#Scenario_6',1,'']]],
  ['common_20cases_13',['Common Cases',['../AdRevenue.html#ad_separation_reasons',1,'']]],
  ['common_20cases_20for_20separation_14',['Common Cases for Separation',['../InAppPurchases.html#iap_separation_reasons',1,'']]],
  ['common_20scenarios_15',['Common Scenarios',['../InAppPurchases.html#iap_scenarios',1,'Common Scenarios'],['../AdRevenue.html#ad_scenarios',1,'Common Scenarios'],['../SubscriptionRevenue.html#sub_scenarios',1,'Common Scenarios']]],
  ['complete_20purchase_20flow_16',['The Complete Purchase Flow',['../InAppPurchases.html#iap_flow',1,'']]],
  ['completion_17',['Scenario 5: Level Start &amp;amp; Completion',['../DummyGameIntegration.html#Scenario_5',1,'']]],
  ['compliance_18',['Compliance',['../DataPrivacy.html#DP_default',1,'Default Privacy Compliance'],['../QuickStart.html#Default',1,'Privacy Compliance']]],
  ['concept_3a_20context_20first_20events_19',['Key Concept: Context-First Events',['../DummyGameIntegration.html#ConceptShift',1,'']]],
  ['configure_20your_20project_20',['Configure your Project',['../QuickStart.html#Configure',1,'']]],
  ['configuring_20consent_20requirement_21',['Configuring Consent Requirement',['../DataPrivacy.html#DP_configure',1,'']]],
  ['conflicts_22',['Merge Conflicts',['../CustomEventsPage.html#custom_events_merge_conflicts',1,'']]],
  ['consent_23',['Consent',['../DataPrivacy.html#DP_consent',1,'Optional User Consent'],['../DummyGameIntegration.html#Scenario_1',1,'Scenario 1: First Launch &amp;amp; Consent'],['../QuickStart.html#Optional',1,'User Consent']]],
  ['consent_20requirement_24',['Configuring Consent Requirement',['../DataPrivacy.html#DP_configure',1,'']]],
  ['consistent_20package_20names_25',['Use Consistent Package Names',['../SubscriptionRevenue.html#sub_consistent_package',1,'']]],
  ['consistent_20placement_20names_26',['Use Consistent Placement Names',['../AdRevenue.html#ad_consistent_placement',1,'']]],
  ['consistent_20product_20ids_27',['Use Consistent Product IDs',['../InAppPurchases.html#iap_product_ids',1,'']]],
  ['context_20first_20events_28',['Key Concept: Context-First Events',['../DummyGameIntegration.html#ConceptShift',1,'']]],
  ['context_20matters_29',['Why Context Matters',['../AdRevenue.html#ad_placement_rationale',1,'']]],
  ['context_20not_20ad_20types_30',['Use Game-Specific Context, Not Ad Types',['../AdRevenue.html#ad_placement_context',1,'']]],
  ['control_31',['Optional Button Click Tracking Control',['../QuickStart.html#ButtonClickControl',1,'']]],
  ['creating_20multiple_20tutorial_20events_32',['Creating Multiple Tutorial Events',['../onboarding_milestone.html#tutorial_multiple',1,'']]],
  ['creating_20tutorial_20custom_20events_33',['Creating Tutorial Custom Events',['../onboarding_milestone.html#tutorial_creation',1,'']]],
  ['credits_20stamp_20card_34',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['critical_35',['Server Validation is Critical',['../InAppPurchases.html#iap_validation_critical',1,'']]],
  ['custom_20error_20reporting_36',['Scenario 11: Custom Error Reporting',['../DummyGameIntegration.html#Scenario_11',1,'']]],
  ['custom_20events_37',['Custom Events',['../CustomEventsPage.html#custom_events_adding',1,'Adding Custom Events'],['../onboarding_milestone.html#tutorial_creation',1,'Creating Tutorial Custom Events'],['../CustomEventsPage.html',1,'Custom Events'],['../EventTypes.html#CustomEventsSection',1,'Custom Events']]],
  ['custom_20tutorial_20events_38',['When to Use Custom Tutorial Events',['../onboarding_milestone.html#tutorial_scenario',1,'']]]
];
