var searchData=
[
  ['a_20broken_20sword_20one_20sided_20transaction_0',['Player Loses a Broken Sword (One-Sided Transaction)',['../ItemExchange.html#Example2',1,'']]],
  ['a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_1',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['a_20reward_20one_20sided_20transaction_2',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['acceptance_20rate_3',['Tracking Ad Offer Acceptance Rate',['../AdRevenue.html#ad_offer_tracking',1,'']]],
  ['across_20all_20apis_4',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['actually_20granted_20items_5',['Actually Granted Items',['../InAppPurchases.html#iap_only_granted_items',1,'Only Report Actually Granted Items'],['../AdRevenue.html#ad_only_granted_items',1,'Only Report Actually Granted Items']]],
  ['ad_20between_20levels_20no_20reward_6',['Scenario 1: Interstitial Ad Between Levels (No Reward)',['../AdRevenue.html#ad_scenario_interstitial',1,'']]],
  ['ad_20items_7',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['ad_20network_20callbacks_8',['Always Use Ad Network Callbacks',['../AdRevenue.html#ad_use_callbacks',1,'']]],
  ['ad_20offer_20acceptance_20rate_9',['Tracking Ad Offer Acceptance Rate',['../AdRevenue.html#ad_offer_tracking',1,'']]],
  ['ad_20revenue_10',['Ad Revenue',['../AdRevenue.html',1,'Ad Revenue'],['../AdRevenue.html#ad_revenue_method',1,'ReportAdRevenue - Track the Ad Revenue']]],
  ['ad_20revenue_20tracking_11',['Ad Revenue Tracking',['../AdRevenue.html#ad_methods',1,'']]],
  ['ad_20revenue_20vs_20iap_12',['Ad Revenue vs IAP',['../AdRevenue.html#ad_distinction',1,'']]],
  ['ad_20types_13',['Use Game-Specific Context, Not Ad Types',['../AdRevenue.html#ad_placement_context',1,'']]],
  ['adding_20custom_20events_14',['Adding Custom Events',['../CustomEventsPage.html#custom_events_adding',1,'']]],
  ['advanced_20game_20features_15',['Tutorials for Advanced Game Features',['../onboarding_milestone.html#advanced_tutorials',1,'']]],
  ['advanced_20item_20goal_20tracking_16',['Scenario 10: Advanced Item &amp;amp; Goal Tracking',['../DummyGameIntegration.html#Scenario_10',1,'']]],
  ['all_20apis_17',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['also_18',['Also',['../InAppPurchases.html#iap_see_also',1,'See Also'],['../AdRevenue.html#ad_see_also',1,'See Also'],['../SubscriptionRevenue.html#sub_see_also',1,'See Also']]],
  ['always_20use_20ad_20network_20callbacks_19',['Always Use Ad Network Callbacks',['../AdRevenue.html#ad_use_callbacks',1,'']]],
  ['an_20item_20',['Defining an &quot;Item&quot;',['../ItemExchange.html#ItemConcept',1,'']]],
  ['analytics_21',['Offline Analytics',['../OfflineAnalytics.html',1,'']]],
  ['and_20a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_22',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['and_20item_20grants_20separate_23',['Why Are Revenue and Item Grants Separate?',['../AdRevenue.html#ad_why_separated',1,'']]],
  ['and_20popups_24',['and Popups',['../Windows.html#tracking-in-game-windows-and-popups',1,'Tracking In-Game Windows and Popups'],['../Windows.html',1,'Windows and Popups']]],
  ['apis_25',['Item Names Identify Items Across All APIs',['../ItemExchange.html#ItemConsistency',1,'']]],
  ['app_20purchases_26',['In-App Purchases',['../InAppPurchases.html',1,'']]],
  ['are_20built_27',['How Funnels Are Built',['../onboarding_milestone.html#ftue_funnel',1,'']]],
  ['are_20granted_28',['Only Call ReportAdItemsGranted When Items Are Granted',['../AdRevenue.html#ad_only_when_granted',1,'']]],
  ['are_20revenue_20and_20item_20grants_20separate_29',['Why Are Revenue and Item Grants Separate?',['../AdRevenue.html#ad_why_separated',1,'']]],
  ['are_20these_20two_20steps_20separated_30',['Why Are These Two Steps Separated?',['../InAppPurchases.html#iap_why_separated',1,'']]],
  ['asynchronous_31',['Scenario 2: Delayed Grant (Asynchronous)',['../InAppPurchases.html#iap_scenario_delayed',1,'']]],
  ['automatic_20event_20types_32',['Automatic Event Types',['../EventTypes.html#AutomaticEvents',1,'']]]
];
