var searchData=
[
  ['team_0',['User Balance Fix Reset by Support Team',['../ItemExchange.html#Example6',1,'']]],
  ['test_20without_20polluting_20production_1',['Safely test without polluting production',['../IntegrationTesting.html#WhyTest',1,'']]],
  ['testing_2',['SDK Integration Testing',['../IntegrationTesting.html',1,'']]],
  ['the_20ad_20revenue_3',['1. ReportAdRevenue - Track the Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'']]],
  ['the_20complete_20purchase_20flow_4',['The Complete Purchase Flow',['../InAppPurchases.html#iap_flow',1,'']]],
  ['the_20items_20delivered_5',['2. ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['the_20monetary_20transaction_6',['1. ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['the_20two_20ad_20revenue_20methods_7',['The Two Ad Revenue Methods',['../AdRevenue.html#ad_methods',1,'']]],
  ['the_20two_20iap_20methods_8',['The Two IAP Methods',['../InAppPurchases.html#iap_methods',1,'']]],
  ['the_20two_20subscription_20methods_9',['The Two Subscription Methods',['../SubscriptionRevenue.html#sub_methods',1,'']]],
  ['these_20two_20methods_20separated_10',['These Two Methods Separated',['../InAppPurchases.html#iap_why_separated',1,'Why Are These Two Methods Separated?'],['../AdRevenue.html#ad_why_separated',1,'Why Are These Two Methods Separated?']]],
  ['time_20user_20experience_20ftue_11',['First-Time User Experience (FTUE)',['../onboarding_milestone.html#ftue_tracking',1,'']]],
  ['to_20double_20reward_12',['Scenario 4: Daily Bonus - Watch to Double Reward',['../AdRevenue.html#ad_scenario_daily_bonus',1,'']]],
  ['to_20get_201_20vial_20of_20eternal_20life_13',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['to_20refill_14',['Scenario 2: Out of Energy - Watch to Refill',['../AdRevenue.html#ad_scenario_rewarded_energy',1,'']]],
  ['to_20use_20custom_20tutorial_20events_15',['When to Use Custom Tutorial Events',['../onboarding_milestone.html#tutorial_scenario',1,'']]],
  ['to_20use_20reportonboardingmilestone_16',['When to Use ReportOnboardingMilestone',['../onboarding_milestone.html#ftue_when',1,'']]],
  ['track_20rewarded_20ad_20items_17',['2. ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['track_20subscriber_20rewards_18',['2. ReportSubscriptionItemsGranted - Track Subscriber Rewards',['../SubscriptionRevenue.html#sub_items_granted_method',1,'']]],
  ['track_20subscription_20billing_19',['1. ReportSubscriptionRevenue - Track Subscription Billing',['../SubscriptionRevenue.html#sub_revenue_method',1,'']]],
  ['track_20the_20ad_20revenue_20',['1. ReportAdRevenue - Track the Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'']]],
  ['track_20the_20items_20delivered_21',['2. ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['track_20the_20monetary_20transaction_22',['1. ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['track_20tutorials_23',['Why Track Tutorials?',['../onboarding_milestone.html#rationale',1,'']]],
  ['tracking_24',['Tracking',['../DummyGameIntegration.html#Scenario_10',1,'Scenario 10: Advanced Item &amp; Goal Tracking'],['../DummyGameIntegration.html#Scenario_4',1,'Scenario 4: FTUE Milestones Tracking'],['../onboarding_milestone.html',1,'Tutorial Tracking']]],
  ['tracking_20control_25',['Optional Button Click Tracking Control',['../QuickStart.html#ButtonClickControl',1,'']]],
  ['tracking_20in_20game_20windows_20and_20popups_26',['Tracking In-Game Windows and Popups',['../Windows.html#tracking-in-game-windows-and-popups',1,'']]],
  ['transaction_27',['Transaction',['../InAppPurchases.html#iap_purchase',1,'1. ReportInAppPurchase - Track the Monetary Transaction'],['../ItemExchange.html#Example2',1,'Player Loses a Broken Sword (One-Sided Transaction)'],['../ItemExchange.html#Example3',1,'Player Receives a Reward (One-Sided Transaction)']]],
  ['trial_20period_28',['Scenario 2: Free Trial Period',['../SubscriptionRevenue.html#sub_scenario_trial',1,'']]],
  ['trip_20changes_20end_20of_20day_20settlement_29',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['trip_20day_3a_20reset_20mid_20trip_20changes_20end_20of_20day_20settlement_30',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['tutorial_20custom_20events_31',['Creating Tutorial Custom Events',['../onboarding_milestone.html#tutorial_creation',1,'']]],
  ['tutorial_20events_32',['Tutorial Events',['../onboarding_milestone.html#tutorial_multiple',1,'Creating Multiple Tutorial Events'],['../onboarding_milestone.html#tutorial_scenario',1,'When to Use Custom Tutorial Events']]],
  ['tutorial_20tracking_33',['Tutorial Tracking',['../onboarding_milestone.html',1,'']]],
  ['tutorials_34',['Tutorials',['../onboarding_milestone.html#tutorial_comparison',1,'FTUE vs Feature Tutorials'],['../onboarding_milestone.html#rationale',1,'Why Track Tutorials?']]],
  ['tutorials_20for_20advanced_20game_20features_35',['Tutorials for Advanced Game Features',['../onboarding_milestone.html#advanced_tutorials',1,'']]],
  ['two_20ad_20revenue_20methods_36',['The Two Ad Revenue Methods',['../AdRevenue.html#ad_methods',1,'']]],
  ['two_20iap_20methods_37',['The Two IAP Methods',['../InAppPurchases.html#iap_methods',1,'']]],
  ['two_20methods_20separated_38',['Two Methods Separated',['../InAppPurchases.html#iap_why_separated',1,'Why Are These Two Methods Separated?'],['../AdRevenue.html#ad_why_separated',1,'Why Are These Two Methods Separated?']]],
  ['two_20subscription_20methods_39',['The Two Subscription Methods',['../SubscriptionRevenue.html#sub_methods',1,'']]],
  ['types_40',['Types',['../EventTypes.html#AutomaticEvents',1,'Automatic Event Types'],['../EventTypes.html',1,'Event Types'],['../EventTypes.html#ManualEvents',1,'Manual Event Types'],['../AdRevenue.html#ad_placement_context',1,'Use Game-Specific Context, Not Ad Types']]]
];
