var searchData=
[
  ['safely_20test_20without_20polluting_20production_0',['Safely test without polluting production',['../IntegrationTesting.html#WhyTest',1,'']]],
  ['scenario_1',['Match3 Level Scenario',['../ItemExchange.html#Example4',1,'']]],
  ['scenario_2010_3a_20advanced_20item_20goal_20tracking_2',['Scenario 10: Advanced Item &amp;amp; Goal Tracking',['../DummyGameIntegration.html#Scenario_10',1,'']]],
  ['scenario_2011_3a_20custom_20error_20reporting_3',['Scenario 11: Custom Error Reporting',['../DummyGameIntegration.html#Scenario_11',1,'']]],
  ['scenario_201_3a_20first_20launch_20consent_4',['Scenario 1: First Launch &amp;amp; Consent',['../DummyGameIntegration.html#Scenario_1',1,'']]],
  ['scenario_201_3a_20immediate_20grant_20synchronous_5',['Scenario 1: Immediate Grant (Synchronous)',['../InAppPurchases.html#iap_scenario_immediate',1,'']]],
  ['scenario_201_3a_20initial_20subscription_20purchase_6',['Scenario 1: Initial Subscription Purchase',['../SubscriptionRevenue.html#sub_scenario_initial',1,'']]],
  ['scenario_201_3a_20interstitial_20ad_20between_20levels_20no_20reward_7',['Scenario 1: Interstitial Ad Between Levels (No Reward)',['../AdRevenue.html#ad_scenario_interstitial',1,'']]],
  ['scenario_202_3a_20delayed_20grant_20asynchronous_8',['Scenario 2: Delayed Grant (Asynchronous)',['../InAppPurchases.html#iap_scenario_delayed',1,'']]],
  ['scenario_202_3a_20free_20trial_20period_9',['Scenario 2: Free Trial Period',['../SubscriptionRevenue.html#sub_scenario_trial',1,'']]],
  ['scenario_202_3a_20out_20of_20energy_20watch_20to_20refill_10',['Scenario 2: Out of Energy - Watch to Refill',['../AdRevenue.html#ad_scenario_rewarded_energy',1,'']]],
  ['scenario_202_3a_20player_20registration_20sign_20in_11',['Scenario 2: Player Registration &amp;amp; Sign-In',['../DummyGameIntegration.html#Scenario_2',1,'']]],
  ['scenario_203_3a_20entering_20main_20menu_20changing_20language_12',['Scenario 3: Entering Main Menu &amp;amp; Changing Language',['../DummyGameIntegration.html#Scenario_3',1,'']]],
  ['scenario_203_3a_20level_20failed_20watch_20for_20extra_20moves_13',['Scenario 3: Level Failed - Watch for Extra Moves',['../AdRevenue.html#ad_scenario_level_failed',1,'']]],
  ['scenario_203_3a_20monthly_20daily_20packages_14',['Scenario 3: Monthly/Daily Packages',['../InAppPurchases.html#iap_scenario_monthly',1,'']]],
  ['scenario_203_3a_20subscription_20renewal_15',['Scenario 3: Subscription Renewal',['../SubscriptionRevenue.html#sub_scenario_renewal',1,'']]],
  ['scenario_204_3a_20bundle_20with_20multiple_20items_16',['Scenario 4: Bundle with Multiple Items',['../InAppPurchases.html#iap_scenario_bundle',1,'']]],
  ['scenario_204_3a_20daily_20bonus_20watch_20to_20double_20reward_17',['Scenario 4: Daily Bonus - Watch to Double Reward',['../AdRevenue.html#ad_scenario_daily_bonus',1,'']]],
  ['scenario_204_3a_20daily_20subscriber_20rewards_18',['Scenario 4: Daily Subscriber Rewards',['../SubscriptionRevenue.html#sub_scenario_daily',1,'']]],
  ['scenario_204_3a_20ftue_20milestones_20tracking_19',['Scenario 4: FTUE Milestones Tracking',['../DummyGameIntegration.html#Scenario_4',1,'']]],
  ['scenario_205_3a_20level_20start_20completion_20',['Scenario 5: Level Start &amp;amp; Completion',['../DummyGameIntegration.html#Scenario_5',1,'']]],
  ['scenario_205_3a_20main_20menu_20banner_20no_20reward_21',['Scenario 5: Main Menu Banner (No Reward)',['../AdRevenue.html#ad_scenario_banner',1,'']]],
  ['scenario_205_3a_20multiple_20item_20rewards_22',['Scenario 5: Multiple Item Rewards',['../SubscriptionRevenue.html#sub_scenario_multiple',1,'']]],
  ['scenario_205_3a_20purchase_20validated_20but_20grant_20fails_23',['Scenario 5: Purchase Validated but Grant Fails',['../InAppPurchases.html#iap_scenario_failed',1,'']]],
  ['scenario_206_3a_20in_20game_20combat_20power_20ups_24',['Scenario 6: In-Game Combat &amp;amp; Power-Ups',['../DummyGameIntegration.html#Scenario_6',1,'']]],
  ['scenario_206_3a_20shop_20watch_20for_20free_20coins_25',['Scenario 6: Shop - Watch for Free Coins',['../AdRevenue.html#ad_scenario_shop',1,'']]],
  ['scenario_207_3a_20multiple_20item_20rewards_26',['Scenario 7: Multiple Item Rewards',['../AdRevenue.html#ad_scenario_multiple_items',1,'']]],
  ['scenario_207_3a_20store_20purchases_20iap_27',['Scenario 7: Store Purchases (IAP)',['../DummyGameIntegration.html#Scenario_7',1,'']]],
  ['scenario_208_3a_20daily_20resets_28',['Scenario 8: Daily Resets',['../DummyGameIntegration.html#Scenario_8',1,'']]],
  ['scenario_209_3a_20non_20unity_20ui_20buttons_20window_20flow_29',['Scenario 9: Non Unity.UI Buttons &amp;amp; Window Flow',['../DummyGameIntegration.html#Scenario_9',1,'']]],
  ['scenarios_30',['Scenarios',['../InAppPurchases.html#iap_scenarios',1,'Common Scenarios'],['../AdRevenue.html#ad_scenarios',1,'Common Scenarios'],['../SubscriptionRevenue.html#sub_scenarios',1,'Common Scenarios'],['../DummyGameIntegration.html#IntegrationScenarios',1,'Integration Scenarios']]],
  ['sdk_20integration_20testing_31',['SDK Integration Testing',['../IntegrationTesting.html',1,'']]],
  ['see_20also_32',['See Also',['../InAppPurchases.html#iap_see_also',1,'See Also'],['../AdRevenue.html#ad_see_also',1,'See Also'],['../SubscriptionRevenue.html#sub_see_also',1,'See Also']]],
  ['separated_33',['Separated',['../InAppPurchases.html#iap_why_separated',1,'Why Are These Two Steps Separated?'],['../AdRevenue.html#ad_why_separated',1,'Why Are These Two Steps Separated?']]],
  ['separation_34',['Common Cases for Separation',['../InAppPurchases.html#iap_separation_reasons',1,'']]],
  ['server_20validation_20is_20critical_35',['Server Validation is Critical',['../InAppPurchases.html#iap_validation_critical',1,'']]],
  ['settlement_36',['Road Trip Day: Reset, Mid-Trip Changes, End-of-Day Settlement',['../ItemExchange.html#Example9',1,'']]],
  ['setuserconsent_20method_37',['SetUserConsent Method',['../DataPrivacy.html#DP_method',1,'']]],
  ['shop_20watch_20for_20free_20coins_38',['Scenario 6: Shop - Watch for Free Coins',['../AdRevenue.html#ad_scenario_shop',1,'']]],
  ['shop_3a_20pay_20with_20voucher_20or_20credits_20stamp_20card_39',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['sided_20transaction_40',['Sided Transaction',['../ItemExchange.html#Example2',1,'Player Loses a Broken Sword (One-Sided Transaction)'],['../ItemExchange.html#Example3',1,'Player Receives a Reward (One-Sided Transaction)']]],
  ['sign_20in_41',['Scenario 2: Player Registration &amp;amp; Sign-In',['../DummyGameIntegration.html#Scenario_2',1,'']]],
  ['specific_20context_20not_20ad_20types_42',['Use Game-Specific Context, Not Ad Types',['../AdRevenue.html#ad_placement_context',1,'']]],
  ['specifications_43',['Data Format Specifications',['../DataFormatSpecs.html',1,'']]],
  ['spends_205_20gold_20coins_20and_20a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_44',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['stamp_20card_45',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['start_20completion_46',['Scenario 5: Level Start &amp;amp; Completion',['../DummyGameIntegration.html#Scenario_5',1,'']]],
  ['start_20guide_47',['Quick Start Guide',['../QuickStart.html',1,'']]],
  ['static_48',['Keep Placement Names Static',['../AdRevenue.html#ad_placement_static',1,'']]],
  ['step_201_3a_20reportadrevenue_20track_20the_20ad_20revenue_49',['Step 1: ReportAdRevenue - Track the Ad Revenue',['../AdRevenue.html#ad_revenue_method',1,'']]],
  ['step_201_3a_20reportinapppurchase_20track_20the_20monetary_20transaction_50',['Step 1: ReportInAppPurchase - Track the Monetary Transaction',['../InAppPurchases.html#iap_purchase',1,'']]],
  ['step_201_3a_20reportsubscriptionrevenue_20track_20subscription_20billing_51',['Step 1: ReportSubscriptionRevenue - Track Subscription Billing',['../SubscriptionRevenue.html#sub_revenue_method',1,'']]],
  ['step_202_3a_20reportaditemsgranted_20track_20rewarded_20ad_20items_52',['Step 2: ReportAdItemsGranted - Track Rewarded Ad Items',['../AdRevenue.html#ad_items_granted_method',1,'']]],
  ['step_202_3a_20reportinapppurchaseitemsgranted_20track_20the_20items_20delivered_53',['Step 2: ReportInAppPurchaseItemsGranted - Track the Items Delivered',['../InAppPurchases.html#iap_items_granted',1,'']]],
  ['step_202_3a_20reportsubscriptionitemsgranted_20track_20subscriber_20rewards_54',['Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards',['../SubscriptionRevenue.html#sub_items_granted_method',1,'']]],
  ['step_20by_20step_20example_20integration_55',['Step-by-Step Example Integration',['../DummyGameIntegration.html',1,'']]],
  ['step_20example_20integration_56',['Step-by-Step Example Integration',['../DummyGameIntegration.html',1,'']]],
  ['steps_57',['Steps',['../AdRevenue.html#ad_methods',1,'The Two Ad Revenue Steps'],['../InAppPurchases.html#iap_methods',1,'The Two IAP Steps'],['../SubscriptionRevenue.html#sub_methods',1,'The Two Subscription Steps']]],
  ['steps_20separated_58',['Steps Separated',['../InAppPurchases.html#iap_why_separated',1,'Why Are These Two Steps Separated?'],['../AdRevenue.html#ad_why_separated',1,'Why Are These Two Steps Separated?']]],
  ['store_20purchases_20iap_59',['Scenario 7: Store Purchases (IAP)',['../DummyGameIntegration.html#Scenario_7',1,'']]],
  ['string_20parameter_20limits_60',['String Parameter Limits',['../InAppPurchases.html#iap_string_limits',1,'String Parameter Limits'],['../AdRevenue.html#ad_string_limits',1,'String Parameter Limits'],['../SubscriptionRevenue.html#sub_string_limits',1,'String Parameter Limits'],['../CustomEventsPage.html#custom_events_string_limits',1,'String Parameter Limits']]],
  ['string_20parameters_61',['String Parameters',['../DataFormatSpecs.html#StringFormat',1,'']]],
  ['subscriber_20rewards_62',['Subscriber Rewards',['../SubscriptionRevenue.html#sub_scenario_daily',1,'Scenario 4: Daily Subscriber Rewards'],['../SubscriptionRevenue.html#sub_items_granted_method',1,'Step 2: ReportSubscriptionItemsGranted - Track Subscriber Rewards']]],
  ['subscription_20billing_63',['Step 1: ReportSubscriptionRevenue - Track Subscription Billing',['../SubscriptionRevenue.html#sub_revenue_method',1,'']]],
  ['subscription_20purchase_64',['Scenario 1: Initial Subscription Purchase',['../SubscriptionRevenue.html#sub_scenario_initial',1,'']]],
  ['subscription_20renewal_65',['Scenario 3: Subscription Renewal',['../SubscriptionRevenue.html#sub_scenario_renewal',1,'']]],
  ['subscription_20revenue_66',['Subscription Revenue',['../SubscriptionRevenue.html',1,'']]],
  ['subscription_20steps_67',['The Two Subscription Steps',['../SubscriptionRevenue.html#sub_methods',1,'']]],
  ['support_20team_68',['User Balance Fix Reset by Support Team',['../ItemExchange.html#Example6',1,'']]],
  ['sword_20one_20sided_20transaction_69',['Player Loses a Broken Sword (One-Sided Transaction)',['../ItemExchange.html#Example2',1,'']]],
  ['synchronous_70',['Scenario 1: Immediate Grant (Synchronous)',['../InAppPurchases.html#iap_scenario_immediate',1,'']]]
];
