var searchData=
[
  ['package_0',['Example: Monthly Login Package',['../InAppPurchases.html#iap_separation_example',1,'']]],
  ['package_20names_1',['Use Consistent Package Names',['../SubscriptionRevenue.html#sub_consistent_package',1,'']]],
  ['packages_2',['Scenario 3: Monthly/Daily Packages',['../InAppPurchases.html#iap_scenario_monthly',1,'']]],
  ['parameter_20limits_3',['Parameter Limits',['../InAppPurchases.html#iap_string_limits',1,'String Parameter Limits'],['../AdRevenue.html#ad_string_limits',1,'String Parameter Limits'],['../SubscriptionRevenue.html#sub_string_limits',1,'String Parameter Limits'],['../CustomEventsPage.html#custom_events_string_limits',1,'String Parameter Limits']]],
  ['parameters_4',['String Parameters',['../DataFormatSpecs.html#StringFormat',1,'']]],
  ['pay_20with_20voucher_20or_20credits_20stamp_20card_5',['Coffee Shop: Pay with Voucher or Credits + Stamp Card',['../ItemExchange.html#Example7',1,'']]],
  ['performance_20first_20ideology_6',['Performance-First Ideology',['../index.html#performance-first-ideology',1,'']]],
  ['performance_20optimizations_7',['Performance Optimizations',['../index.html#performance-optimizations',1,'']]],
  ['period_8',['Scenario 2: Free Trial Period',['../SubscriptionRevenue.html#sub_scenario_trial',1,'']]],
  ['placement_20names_9',['Use Consistent Placement Names',['../AdRevenue.html#ad_consistent_placement',1,'']]],
  ['placement_20names_20static_10',['Keep Placement Names Static',['../AdRevenue.html#ad_placement_static',1,'']]],
  ['placement_20naming_20best_20practices_11',['Placement Naming Best Practices',['../AdRevenue.html#ad_placement_naming',1,'']]],
  ['placement_20naming_20examples_12',['Placement Naming Examples',['../AdRevenue.html#ad_placement_examples',1,'']]],
  ['player_20loses_20a_20broken_20sword_20one_20sided_20transaction_13',['Player Loses a Broken Sword (One-Sided Transaction)',['../ItemExchange.html#Example2',1,'']]],
  ['player_20receives_20a_20reward_20one_20sided_20transaction_14',['Player Receives a Reward (One-Sided Transaction)',['../ItemExchange.html#Example3',1,'']]],
  ['player_20registration_20sign_20in_15',['Scenario 2: Player Registration &amp;amp; Sign-In',['../DummyGameIntegration.html#Scenario_2',1,'']]],
  ['player_20spends_205_20gold_20coins_20and_20a_20healing_20potion_20to_20get_201_20vial_20of_20eternal_20life_16',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['polluting_20production_17',['Safely test without polluting production',['../IntegrationTesting.html#WhyTest',1,'']]],
  ['popups_18',['Popups',['../Windows.html#tracking-in-game-windows-and-popups',1,'Tracking In-Game Windows and Popups'],['../Windows.html',1,'Windows and Popups']]],
  ['potion_20to_20get_201_20vial_20of_20eternal_20life_19',['Player Spends 5 Gold Coins and a Healing Potion to Get 1 Vial of Eternal Life',['../ItemExchange.html#Example1',1,'']]],
  ['power_20ups_20',['Scenario 6: In-Game Combat &amp;amp; Power-Ups',['../DummyGameIntegration.html#Scenario_6',1,'']]],
  ['practices_21',['Practices',['../InAppPurchases.html#iap_best_practices',1,'Best Practices'],['../AdRevenue.html#ad_best_practices',1,'Best Practices'],['../SubscriptionRevenue.html#sub_best_practices',1,'Best Practices'],['../AdRevenue.html#ad_placement_naming',1,'Placement Naming Best Practices']]],
  ['prices_20must_20be_20in_20usd_20cents_22',['Prices Must Be in USD Cents',['../InAppPurchases.html#iap_price_usd',1,'']]],
  ['principles_23',['Design Principles',['../index.html#design-principles',1,'']]],
  ['privacy_24',['Data Privacy',['../DataPrivacy.html',1,'']]],
  ['privacy_20compliance_25',['Privacy Compliance',['../DataPrivacy.html#DP_default',1,'Default Privacy Compliance'],['../QuickStart.html#Default',1,'Privacy Compliance']]],
  ['product_20ids_26',['Use Consistent Product IDs',['../InAppPurchases.html#iap_product_ids',1,'']]],
  ['production_27',['Safely test without polluting production',['../IntegrationTesting.html#WhyTest',1,'']]],
  ['project_28',['Configure your Project',['../QuickStart.html#Configure',1,'']]],
  ['purchase_29',['Scenario 1: Initial Subscription Purchase',['../SubscriptionRevenue.html#sub_scenario_initial',1,'']]],
  ['purchase_20flow_30',['The Complete Purchase Flow',['../InAppPurchases.html#iap_flow',1,'']]],
  ['purchase_20once_20only_31',['Report Purchase Once Only',['../InAppPurchases.html#iap_report_once',1,'']]],
  ['purchase_20validated_20but_20grant_20fails_32',['Scenario 5: Purchase Validated but Grant Fails',['../InAppPurchases.html#iap_scenario_failed',1,'']]],
  ['purchases_33',['In-App Purchases',['../InAppPurchases.html',1,'']]],
  ['purchases_20iap_34',['Scenario 7: Store Purchases (IAP)',['../DummyGameIntegration.html#Scenario_7',1,'']]]
];
